config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :skip => [:registration]
  root "home#index"
  resources :home
  resources :items
  resources :orders
  resources :customers
  resources :sellers do
    resources :products
  end

  get "/seller/:seller_id/show_pruducts", to: "products#show_products", as: "show_products"
end

app/models/seller.rb
class Seller < ApplicationRecord
    has_one :user, as: :type_id, dependent: :destroy
    accepts_nested_attributes_for :user

    has_many :products

    validates :name, :address, :status, presence: true
    validates :name, length: { minimum: 3 }
end

app/controllers/sellers_controller.rb
class SellersController < ApplicationController
    def index
        @sellers = Seller.all
    end

    def show
        @seller = current_user.type_id
    end

    def new
        @seller = Seller.new
        @seller.build_user
    end

    def edit
        @seller = current_user.type_id
    end

    def create
        @seller = Seller.new(seller_params)
        respond_to do |format|
            if @seller.save
                format.html { redirect_to new_user_session_path, notice: 'Seller was successfully created.' }
                format.json { render :show, status: :created, location: @seller }
            else
                format.html { render :new }
                format.json { render json: @seller.errors, status: :unprocessable_entity }
            end
        end
    end

    def update
        respond_to do |format|
            if @seller.update(seller_params)
                format.html { redirect_to @seller, notice: 'Seller was successfully updated.' }
                format.json { render :show, status: :ok, location: @seller }
            else
                format.html { render :edit }
                format.json { render json: @seller.errors, status: :unprocessable_entity }
            end
        end
    end

    def destroy
        @seller.destroy
        respond_to do |format|
            format.html { redirect_to sellers_url, notice: 'Seller was successfully destroyed.' }
            format.json { head :no_content }
        end
    end

    private
        def seller_params
            params.require(:seller).permit(:name, :address, :status, user_attributes: [ :id, :email, :password, :password_confirmation ])
        end
end

app/views/sellers/_form.html.erb
<style>
    span{
        color : red;
    }
</style>

<%= form_for(@seller) do |f| %>

    <div class = "row" style = "text-align: center;">
        <div class = "col-lg-6">
            <%= f.label :name %><br>
            <%= f.text_field :name %>
            <% @seller.errors.full_messages_for(:name).each do |message| %>
                <span><%= message %></span><br>
            <% end %>
        </div>

        <div class = "col-lg-6">
            <%= f.label :Address %><br>
            <%= f.text_area :address %>
            <% @seller.errors.full_messages_for(:address).each do |message| %>
                <span><%= message %></span>
            <% end %>
        </div>

        <div class = "col-lg-6">
            <%= f.label :Status %><br>
            <%= f.radio_button :status, "open", class: "form-check-radio" %>
            <%= f.label :status_open, "Open" %>
            <%= f.radio_button :status, "close", class: "form-check-radio" %>
            <%= f.label :status_close, "Close" %><br>
            <% @seller.errors.full_messages_for(:status).each do |message| %>
                <span><%= message %></span>
            <% end %>
        </div>

        <%= f.fields_for :user do |u| %>
            <div class = "col-lg-6">
                <%= u.label :email %><br>
                <%= u.text_field :email %>
                <% @seller.user.errors.full_messages_for(:email).each do |message| %>
                    <span><%= message %></span>
                <% end %>
            </div>

            <div class = "col-lg-6">
                <%= u.label :password %><br>
                <%= u.password_field :password %>
                <% @seller.user.errors.full_messages_for(:password).each do |message| %>
                    <span><%= message %></span>
                <% end %>
            </div>

            <div class = "col-lg-6">
                <%= u.label :password_confirmation %><br>
                <%= u.password_field :password_confirmation %>
                <% @seller.user.errors.full_messages_for(:password_confirmation).each do |message| %>
                    <span><%= message %></span>
                <% end %>
            </div>
        <% end %>

        <div class = "col-lg-12" style = "margin: 10px 0px; text-align: center;">
            <%= f.submit "Submit", :class => "btn btn-info" %>
        </div>
    </div>
<% end %>

app/views/sellers/edit.html.erb
<div class = "container">
    <center><h1>Editing Seller</h1></center>
    <%= render 'form' %>

    <div style = "margin: 20px auto; text-align: center">
        <%= link_to 'Show', @seller, class: "btn btn-success" %>
        <%= link_to 'Back', seller_path(current_user.type_id), class: "btn btn-warning" %>
    </div>
</div>

app/views/sellers/index.html.erb
<div id = "intro">
    <div class = "container">
        <ul class="nav nav-pills nav-justified">
            <li class="nav-item"><%= link_to 'View All Product', show_products_path(current_user.type_id) %></li>
            <li class="nav-item"><%= link_to 'Add New Product', new_seller_product_path(current_user.type_id) %></li>
        </ul>
    </div>
</div>

app/views/sellers/new.html.erb
<div class = "container">
    <center><h1>New Seller</h1></center>
    <%= render 'form' %>
</div>

app/views/sellers/show.html.erb
<div class = "container">
    <center><h1>Show Seller Details</h1>
    <table class = "table table-hover table-borderless w-auto">
        <tbody>
            <tr>
                <th>Name</th>
                <td><%= @seller.name %></td>
            </tr>
        </tbody>
        <tbody>
            <tr>
                <th>Email</th>
                <td><%= @seller.user.email %></td>
            </tr>
        </tbody>
        <tbody>
            <tr>
                <th>Address</th>
                <td><%= @seller.address %></td>
            </tr>
        </tbody>
        <tbody>
            <tr>
                <th>Status</th>
                <td><%= @seller.status %></td>
            </tr>
        </tbody>
    </table></center>
    <div style = "margin: 20px auto; text-align: center">
        <%= link_to 'Edit', edit_seller_path(@seller), class: "btn btn-success" %>
        <%= link_to 'Back', root_path, class: "btn btn-warning" %>
    </div>
</div>