config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :skip => [:registration]
  root "home#index"
  resources :home
  resources :items
  resources :orders
  resources :customers
  resources :sellers do
    resources :products
  end

  get "/seller/:seller_id/show_pruducts", to: "products#show_products", as: "show_products"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @seller = Seller.all
  end

  def show
    @seller = Seller.find(params[:id])
    @category = Category.all
    @products = Product.joins(:category).where("categories.name = ?", @category.first.name)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<section id = "home" name = "home"></section>
<div id = "headerwrap">
    <div class = "container">
        <div class = "row text-center">
            <div class = "col-lg-12">
                <% unless user_signed_in? %>
                    <h1>Welcome Guest!!</h1>
                <% else %>
                    <div style = "position: relative; width: 900px; margin: 0px auto;">
                        <h1>Welcome <b><%= current_user.type_id.name %></b>!!</h1>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

<% unless user_signed_in? %>
    <div id = "headerwrap">
        <div class = "container">
            <h3>Login or Sign Up first to continue.....</h3>
        </div>
    </div>
<% else %>
    <% if current_user.type_id_type == "Customer" %>
        <div id = "headerwrap">
            <div class = "container">
                <div class = "row text-center">
                    <div class = "col-lg-12">
                        <div style = "position: relative; width: 900px; margin: 0px auto;">
                            <h3>Are you hungry?</h3>
                            <form class="d-flex">
                                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                                <button class="btn btn-success" type="submit">Search</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <%= render template: "customers/index" %>
    <% else %>
        <%= render template: "sellers/index" %>
    <% end %>
<% end %>

app/views/home/show.html.erb
<div id = "showcase">
    <div class = "container">
        <div class = "text-center">
            
            <h1><%= @seller.name %></h1>
            <p><%= @seller.address %></p>
            <% if (@seller.status == "open")%>
                <h4><span class="badge rounded-pill bg-success">Open</span></h4>
            <% else %>
                <h4><span class="badge rounded-pill bg-danger">Close</span></h4>
            <% end %>
        </div>
        <div>
            <ul class="nav nav-pills nav-justified">
                <% @category.each do |category| %>
                    <li class="nav-item category-li">
                        <a class="nav-link">
                            <%= link_to category.name, seller_products_path(@seller.id, category: category.name), class: "nav-link", remote: true %>
                        </a>
                    </li>
                <% end %>
            </ul>
        </div>
        <% if params[:category].present? %>
            <div>
                <h4><%= params[:category] %></h4>
                <table class = "table table-borderless">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Price</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <% @products.each do |product| %>
                            <tr>
                                <% if product.description.present? %>
                                    <td><%= product.name %> (<%= product.description %>)</td>
                                <% else %>
                                    <td><%= product.name %></td>
                                <% end %>
                                <td><%= product.price  %></td>
                                <% if product.available? %>
                                    <td>
                                        <%= form_for Item.new, url: items_path do |f| %>
                                            <%= f.hidden_field :seller_id, :value => @seller.id %>
                                            <%= f.hidden_field :product_id, :value => product.id %>
                                            <%= f.number_field :quantity, :value => 1, :min => 1 %>
                                            <%= f.submit "Add to Cart", class: "btn btn-primary"%>
                                        <% end %>
                                    </td>
                                <% else %>
                                    <td><h5><span class = "badge rounded-pill bg-danger">Not available</span></h5></td>
                                <% end %>
                            </tr>
                        <% end %>
                    </tbody>
                </table>
            </div>
        <% end %>
    </div>
</div>