config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :skip => [:registration]
  root "home#index"
  resources :home
  resources :items
  resources :orders
  resources :customers
  resources :sellers do
    resources :products
  end

  get "/seller/:seller_id/show_pruducts", to: "products#show_products", as: "show_products"
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :product
  belongs_to :cart, optional: true
  belongs_to :order, optional: true

  validate :check_seller

  def check_seller
    unless self.cart.items.first.product.seller_id == self.product.seller_id
      errors.add(:base, 'Prodect can not be added for different seller!!!')
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	def index
		@items = current_cart.items
	end
	
    def create
		item = current_cart.items.new(item_params)
		if item.save
		  redirect_to home_path(item.product.seller_id)
		else
			redirect_to home_path(item.product.seller_id), notice: item.errors.full_messages.join(",")
		end
    end

	def update
		item = current_cart.items.find(params[:id])
		item.update(item_params)
		redirect_to items_path
	end

	def destroy
		item = current_cart.items.find(params[:id])
		item.destroy
		redirect_to items_path
	end

    private
			def item_params
				params.require(:item).permit(:quantity, :product_id)
			end
end

app/views/items/index.html.erb
<div id="showcase">
    <marquee><h2>Total amount to be paid: <%= total_amount %></h2></marquee>
    <center><%= button_to "Order Now", orders_path, method: :post, class: "btn btn-primary"%></center>
    <table class="table table-borderless">
        <thead>
            <tr>
                <th>Name</th>
                <th>Unit Price</th>
                <th>Quantity</th>
                <th>Total Price</th>
            </tr>
        </thead>
        <tbody>
            <% @items.each do |item| %>
                <tr>
                    <td><%= item.product.name %></td>
                    <td><%= item.product.price %></td>
                    <td>
                        <%= form_for item do |f|%>
                            <%= f.hidden_field :product_id, :value => item.product.id %>
                            <%= f.number_field :quantity, :value => item.quantity, :min => 1 %>
                            <%= f.submit "Update", class: "btn btn-info"%>
                        <% end %>
                        <%= button_to "Remove", item_path(item), method: :delete, class: "btn btn-danger"%>
                    </td>
                    <td><%= (item.product.price*item.quantity) %></td>
                </tr>
            <% end %>
        </tbody>
    </table>
</div>