config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :skip => [:registration]
  root "home#index"
  resources :home
  resources :items
  resources :orders
  resources :customers
  resources :sellers do
    resources :products
  end

  get "/seller/:seller_id/show_pruducts", to: "products#show_products", as: "show_products"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :customer
  has_many :items
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products
end

app/models/customer.rb
class Customer < ApplicationRecord
    has_one :user, as: :type_id, dependent: :destroy
    has_many :carts
    has_many :orders
    accepts_nested_attributes_for :user

    validates :name, :contact_no, :address, presence: true
    validates :contact_no, length: { is: 10 }
    validates :name, length: { minimum: 3 }
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :product
  belongs_to :cart, optional: true
  belongs_to :order, optional: true

  validate :check_seller

  def check_seller
    unless self.cart.items.first.product.seller_id == self.product.seller_id
      errors.add(:base, 'Prodect can not be added for different seller!!!')
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  belongs_to :seller
  has_many :items
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  belongs_to :seller
  
  validates :name, :category_id, :price, presence: true
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :seller
  belongs_to :customer
end

app/models/seller.rb
class Seller < ApplicationRecord
    has_one :user, as: :type_id, dependent: :destroy
    accepts_nested_attributes_for :user

    has_many :products

    validates :name, :address, :status, presence: true
    validates :name, length: { minimum: 3 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Associtaion
  belongs_to :type_id, polymorphic: true, :dependent => :destroy
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @seller = Seller.all
  end

  def show
    @seller = Seller.find(params[:id])
    @category = Category.all
    @products = Product.joins(:category).where("categories.name = ?", @category.first.name)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	def index
		@items = current_cart.items
	end
	
    def create
		item = current_cart.items.new(item_params)
		if item.save
		  redirect_to home_path(item.product.seller_id)
		else
			redirect_to home_path(item.product.seller_id), notice: item.errors.full_messages.join(",")
		end
    end

	def update
		item = current_cart.items.find(params[:id])
		item.update(item_params)
		redirect_to items_path
	end

	def destroy
		item = current_cart.items.find(params[:id])
		item.destroy
		redirect_to items_path
	end

    private
			def item_params
				params.require(:item).permit(:quantity, :product_id)
			end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	def show
		@order = Order.find(params[:id])
		@items = @order.items.all
	end

  def create
		customer = current_user.type_id
		seller_id = current_cart.items.first.product.seller_id
		@order = customer.orders.new(seller_id: seller_id, price: total_amount)        
		@order.save
		current_cart.items.update_all(cart_id: nil, order_id: @order.id)
		redirect_to @order
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :load_seller
    def index
	    params[:category] = Category.first.name if params[:category].blank?
      @products = @seller.products.joins(:category).where("categories.name = ?", params[:category])
      @category = Category.all
      render "home/show"
    end

    def show_products
      @category = Category.all
      @products = @seller.products.all
    end

    def new
		@category = Category.all
		@product = @seller.products.new
    end

    def edit
    end

    def create
		@category = Category.all
		@product = @seller.products.new(product_params)
		if @product.save
			redirect_to root_path
		else
			render :new, status: :unprocessable_entity
		end
    end

    def update
    end

    def destroy
    end

    private
        def product_params
          params.require(:product).permit(:name, :category_id, :description, :price, :available)
        end

        def load_seller
          @seller = Seller.find(params[:seller_id])
        end
end

app/controllers/sellers_controller.rb
class SellersController < ApplicationController
    def index
        @sellers = Seller.all
    end

    def show
        @seller = current_user.type_id
    end

    def new
        @seller = Seller.new
        @seller.build_user
    end

    def edit
        @seller = current_user.type_id
    end

    def create
        @seller = Seller.new(seller_params)
        respond_to do |format|
            if @seller.save
                format.html { redirect_to new_user_session_path, notice: 'Seller was successfully created.' }
                format.json { render :show, status: :created, location: @seller }
            else
                format.html { render :new }
                format.json { render json: @seller.errors, status: :unprocessable_entity }
            end
        end
    end

    def update
        respond_to do |format|
            if @seller.update(seller_params)
                format.html { redirect_to @seller, notice: 'Seller was successfully updated.' }
                format.json { render :show, status: :ok, location: @seller }
            else
                format.html { render :edit }
                format.json { render json: @seller.errors, status: :unprocessable_entity }
            end
        end
    end

    def destroy
        @seller.destroy
        respond_to do |format|
            format.html { redirect_to sellers_url, notice: 'Seller was successfully destroyed.' }
            format.json { head :no_content }
        end
    end

    private
        def seller_params
            params.require(:seller).permit(:name, :address, :status, user_attributes: [ :id, :email, :password, :password_confirmation ])
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def current_cart
        cart_id = session[:cart_id]
        cart = Cart.find(cart_id) if cart_id
        if cart.blank?
            cart = current_user.type_id.carts.find_or_create_by(customer_id: current_user.type_id_id)
            session[:cart_id] = cart.id
        end
        cart
    end

    def total_amount
        sum = 0
        current_cart.items.each do |item|
            sum += item.product.price*item.quantity
        end
        sum
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/_footer.html.erb
<section id = "contact" name = "contact"></section>
<div id = "footerwrap">
    <div class = "container">
        <div class = "col-lg-5">
            <h3>Contact</h3>
            <p><b>Github:</b> <a href = "https://github.com/LalakGarg" target = "_blank">@LalakGarg</a></p>
            <p><b>Email:</b> <a href = "mailto:lalak@webkorps.com">lalak@webkorps.com</a></p>
        </div>
        <div class = "col-lg-7">
            <h3>About The Project</h3><br>
            This is a demo project given by the company to learn <strong>Ruby on Rails</strong>. In this project there are two users <strong>Customer</strong> and <strong>Seller</strong>. It works as <strong>Online Food Ordering Application</strong> link <strong>Swiggy</strong>.
        </div>
    </div>
</div>
<div id = "c">
    <div class = "container">
        <p>Created using Visual Studio Code</p>
    </div>
</div>

app/views/layouts/_navbar.html.erb
<div id = "navigation" class = "navbar navbar-default nav-fixed-top">
    <div class = "container">
        <div class = "navbar-header">
            <%= link_to image_tag("logo.png"), root_path,  :title => "title text" , class: "navbar-brand" %>
        </div>
        <ul class = "nav navbar-nav">
            <li><%= link_to "Home", root_path %></li>
            <% unless user_signed_in? %>
                <li><%= link_to("Customer Registration", new_customer_path) %></li>
                <li><%= link_to("Seller Registration", new_seller_path) %></li>
                <li><%= link_to("Login", new_user_session_path) %></li>
            <% else %>
                <% if current_user.type_id_type == "Customer" %>
                    <li><%= link_to 'Customers', customer_path(current_user.type_id) %></li>
                    <li><%= link_to "Cart (#{current_cart.items.count})", items_path %></li>
                <% else %>
                    <li><%= link_to 'Sellers', seller_path(current_user.type_id) %></li>
                <% end %>
                <li><%= button_to 'Logout', destroy_user_session_path, method: :delete, class: "btn btn-success" %></li>
            <% end %>
        </ul>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Online Food!!</title>
    <%= favicon_link_tag asset_path('icon.png'), :rel => 'icon', :type =>  'image/png' %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <script type="text/javascript"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "style" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <% if notice.present? || alert.present? %>
      <p class = "notice"><%= notice %></p>
      <p class = "alert"><%= alert%></p>
    <% end %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>